### PR TITLE
Make FASTERDistributedCache public + make services arg nullable with …

### PR DESCRIPTION
**Pull request by jodydonetti**
…sensible defaults

### CODE REVIEW

**Comment by jodydonetti** [comment]
Fixes #1 (maybe?)

**Comment by jodydonetti** [comment]
Also: I wanted to make the `services` arg optional (`IServiceProvider? services = null`), but was not sure if optional args in the ctor is something to avoid for some reason, I saw hints of that in the dotnet codebase.

**Comment by mgravell** [comment]
As you can see, right now the .ctor is designed for service injection. If we want explicit/manual construction, my main thinking here is that maybe a "builder" pattern is preferable here. My concern is that we might want to play fast and loose with the constructor, which is a binary break - a builder might mask that; thoughts?

**Comment by jodydonetti** [comment]
Ah, you're right I haven't thought about that.

And yes, a builder would prob be the best approach, even more so when fast iterating.

**Comment by mgravell** [comment]
I went with the builder API, plus I refactored a bit of the clock logic so both clock types are usable interchangeably (when available) - https://github.com/mgravell/FASTERCache/commit/cd5a5786a47db98cb7fc6f84b7657125f36bd104

**Comment by mgravell** [comment]
hugely appreciated, though!

**Comment by jodydonetti** [comment]
Great!

**Pull request closed without merging**
